apiVersion: apps/v1
kind: Deployment
metadata: 
    name: jobzbuzz-backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jobzbuzz-backend-app
    template:
        metadata:
           labels:
              app: jobzbuzz-backend-app
        spec:
           
           containers:
              - name: jobzbuzz-container
                image: registry-server:5000/jobzbuzz-bckend:v1.0
                
                
---
apiVersion: v1
kind: Service
metadata:
    name: jb-ftnd-svc
spec:
   selector:
        app: jobzbuzz-backend-app
   type: NodePort
   ports:
     - port: 8000
       targetPort: 8000
       nodePort: 30004
